item {
  name: 'aluminium'
  id: 1
  
}
item {
  name: 'can'
  id: 2
  
}
item {
  name: 'glass'
  id: 3
 
}
item {
  name: 'kitchen'
  id: 4
  
}
item {
  name: 'plastic'
  id: 5
  
}
item {
  name: 'cloth'
  id: 6
  
}
item {
  name: 'wood'
  id: 7
  
}
